// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }


// import NavBar from "@/components/NavBar";
// import Providers from "./providers";

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body className="min-h-screen">
//         <Providers>
//           <NavBar />    {/* <-- client component can be nested */}
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
// src/app/layout.tsx
import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";  // ← import the font instances
import "./globals.css";
import Providers from "./providers";
import NavBar from "@/components/NavBar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Yung Salita",
  description: "Crowdsourced slang across languages",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // ① Attach the CSS variables for Geist fonts to <html>
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      {/* ② Apply the GeistSans variable via Tailwind’s font-sans utility */}
      <body className="min-h-screen font-sans antialiased">
        <Providers>
          {/* ③ Wrap your client-only NavBar in Suspense */}
          <Suspense fallback={null}>
            <NavBar />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  );
}
