// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }


// import NavBar from "@/components/NavBar";
// import Providers from "./providers";

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body className="min-h-screen">
//         <Providers>
//           <NavBar />    {/* <-- client component can be nested */}
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import Providers from "./providers";
import NavBar from "@/components/NavBar";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";
import { Analytics } from "@vercel/analytics/next";
import { DeferredAchievementLoader } from "@/components/achievements/DeferredAchievementLoader";

export const metadata: Metadata = {
  title: {
    template: "%s | Yung Salita",
    default: "Yung Salita - The Global Urban Dictionary",
  },
  description: "Discover and contribute to the world's largest multilingual urban dictionary. Learn slang, phrases, and expressions from languages around the globe with definitions, examples, and cultural context.",
  keywords: ["slang", "urban dictionary", "multilingual", "phrases", "definitions", "language learning", "cultural expressions"],
  authors: [{ name: "Yung Salita Community" }],
  creator: "Yung Salita",
  publisher: "Yung Salita",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(process.env.NEXTAUTH_URL || "https://yungsalita.com"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Yung Salita - The Global Urban Dictionary",
    description: "Discover and contribute to the world's largest multilingual urban dictionary. Learn slang, phrases, and expressions from languages around the globe.",
    url: "/",
    siteName: "Yung Salita",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/yungsalita.png",
        width: 1200,
        height: 630,
        alt: "Yung Salita - The Global Urban Dictionary",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Yung Salita - The Global Urban Dictionary",
    description: "Discover and contribute to the world's largest multilingual urban dictionary.",
    images: ["/yungsalita.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // ① Attach the CSS variables for Geist fonts to <html>
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <head>
        {/* Preconnect to Google's image CDN for faster avatar loading */}
        <link rel="preconnect" href="https://lh3.googleusercontent.com" />
        <link rel="dns-prefetch" href="https://lh3.googleusercontent.com" />
      </head>
      {/* ② Apply the GeistSans variable via Tailwind's font-sans utility */}
      <body className="min-h-screen font-sans antialiased">
        <Analytics />
        <Providers>
          {/* ③ Wrap your client-only NavBar in Suspense */}
          <Suspense fallback={null}>
            <NavBar />
          </Suspense>
          {children}
          <DeferredAchievementLoader />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
